//go:build go1.16
// +build go1.16

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package securitygrouprule_test

import (
	"context"
	"testing"

	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/internal/recording"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/scenario_test"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
)

var (
	ctx               context.Context
	cred              azcore.TokenCredential
	pathToPackage     = "sdk/resourcemanager/network/armnetwork/scenario_test/securitygrouprule/testdata"
	options           *arm.ClientOptions
	resourceGroup     *armresources.ResourceGroup
	resourceName      string
	location          = scenario_test.GetEnv("LOCATION", "eastus")
	resourceGroupName = scenario_test.GetEnv("RESOURCE_GROUP_NAME", "")
	subscriptionId    = scenario_test.GetEnv("SUBSCRIPTION_ID", scenario_test.GetEnv("AZURE_SUBSCRIPTION_ID", ""))
)

func TestSecuritygrouprule(t *testing.T) {
	// Setup for test
	scenario_test.StartRecording(t, pathToPackage)
	ctx = context.Background()
	options = scenario_test.CreateArmOptions(t)
	cred = scenario_test.CreateCred(t, ctx, options)
	resourceGroup = scenario_test.CreateResourceGroup(t, ctx, cred, subscriptionId, location, options)
	resourceGroupName = *resourceGroup.Name
	// Clenup for test
	t.Cleanup(func() {
		scenario_test.DeleteResourceGroup(t, ctx, cred, subscriptionId, resourceGroupName, options)
		scenario_test.StopRecording(t)
	})
	prepare(t)
	scenarioNetworksecuritygrouprules(t)
	cleanup(t)
}

func prepare(t *testing.T) {
	// From step Generate_Unique_Name
	{
		template := map[string]interface{}{
			"$schema":        "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
			"contentVersion": "1.0.0.0",
			"outputs": map[string]interface{}{
				"resourceName": map[string]interface{}{
					"type":  "string",
					"value": "[variables('name').value]",
				},
			},
			"resources": []interface{}{},
			"variables": map[string]interface{}{
				"name": map[string]interface{}{
					"type": "string",
					"metadata": map[string]interface{}{
						"description": "Name of the Resource Group.",
					},
					"value": "[concat('sw',uniqueString(resourceGroup().id))]",
				},
			},
		}
		params := map[string]interface{}{}
		deploymentExtend, err := scenario_test.CreateDeployment(ctx, cred, options, subscriptionId, resourceGroupName, "Generate_Unique_Name", template, params)
		if err != nil {
			t.Fatalf("Deployment error: %v", err)
		}
		resourceName = deploymentExtend.Properties.Outputs["resourceName"].(map[string]interface{})["value"].(string)
	}
}

func scenarioNetworksecuritygrouprules(t *testing.T) {
	// From step SecurityGroups_BeginCreateOrUpdate
	securityGroupsClient := armnetwork.NewSecurityGroupsClient(subscriptionId, cred, options)
	{
		securityGroupsClientCreateOrUpdatePollerResponse, err := securityGroupsClient.BeginCreateOrUpdate(ctx,
			resourceGroupName,
			"testnsg",
			armnetwork.SecurityGroup{
				Location: to.StringPtr(location),
			},
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		var response armnetwork.SecurityGroupsClientCreateOrUpdateResponse
		if recording.GetRecordMode() == recording.PlaybackMode {
			for {
				_, err = securityGroupsClientCreateOrUpdatePollerResponse.Poller.Poll(ctx)
				if err != nil {
					t.Fatalf("Request error: %v", err)
				}
				if securityGroupsClientCreateOrUpdatePollerResponse.Poller.Done() {
					response, err = securityGroupsClientCreateOrUpdatePollerResponse.Poller.FinalResponse(ctx)
					if err != nil {
						t.Fatalf("Request error: %v", err)
					}
					break
				}
			}
		} else {
			response, err = securityGroupsClientCreateOrUpdatePollerResponse.PollUntilDone(ctx, 10*time.Second)
			if err != nil {
				t.Fatalf("Request error: %v", err)
			}
		}
		t.Logf("Response result: %#v\n", response.SecurityGroupsClientCreateOrUpdateResult)
	}

	// From step SecurityGroupRules_Create
	securityRulesClient := armnetwork.NewSecurityRulesClient(subscriptionId, cred, options)
	{
		securityRulesClientCreateOrUpdatePollerResponse, err := securityRulesClient.BeginCreateOrUpdate(ctx,
			resourceGroupName,
			"testnsg",
			"rule1",
			armnetwork.SecurityRule{
				Properties: &armnetwork.SecurityRulePropertiesFormat{
					Access:                   armnetwork.SecurityRuleAccessDeny.ToPtr(),
					DestinationAddressPrefix: to.StringPtr("11.0.0.0/8"),
					DestinationPortRange:     to.StringPtr("8080"),
					Direction:                armnetwork.SecurityRuleDirectionOutbound.ToPtr(),
					Priority:                 to.Int32Ptr(100),
					SourceAddressPrefix:      to.StringPtr("10.0.0.0/8"),
					SourcePortRange:          to.StringPtr("*"),
					Protocol:                 armnetwork.SecurityRuleProtocolAsterisk.ToPtr(),
				},
			},
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		var response armnetwork.SecurityRulesClientCreateOrUpdateResponse
		if recording.GetRecordMode() == recording.PlaybackMode {
			for {
				_, err = securityRulesClientCreateOrUpdatePollerResponse.Poller.Poll(ctx)
				if err != nil {
					t.Fatalf("Request error: %v", err)
				}
				if securityRulesClientCreateOrUpdatePollerResponse.Poller.Done() {
					response, err = securityRulesClientCreateOrUpdatePollerResponse.Poller.FinalResponse(ctx)
					if err != nil {
						t.Fatalf("Request error: %v", err)
					}
					break
				}
			}
		} else {
			response, err = securityRulesClientCreateOrUpdatePollerResponse.PollUntilDone(ctx, 10*time.Second)
			if err != nil {
				t.Fatalf("Request error: %v", err)
			}
		}
		t.Logf("Response result: %#v\n", response.SecurityRulesClientCreateOrUpdateResult)
	}

	// From step SecurityGroupRules_Get
	{
		securityRulesClientGetResponse, err := securityRulesClient.Get(ctx,
			resourceGroupName,
			"testnsg",
			"rule1",
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		t.Logf("Response result: %#v\n", securityRulesClientGetResponse.SecurityRulesClientGetResult)
	}

	// From step SecurityGroupRules_List
	{
		securityRulesClientListPager := securityRulesClient.List(resourceGroupName,
			"testnsg",
			nil)
		for securityRulesClientListPager.NextPage(ctx) {
			if err := securityRulesClientListPager.Err(); err != nil {
				t.Fatalf("Failed to advance page: %v", err)
			}
			for _, v := range securityRulesClientListPager.PageResponse().Value {
				t.Logf("Pager result: %#v\n", v)
			}
		}
	}

	// From step SecurityGroupRules_Delete
	{
		securityRulesClientDeletePollerResponse, err := securityRulesClient.BeginDelete(ctx,
			resourceGroupName,
			"testnsg",
			"rule1",
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		if recording.GetRecordMode() == recording.PlaybackMode {
			for {
				_, err = securityRulesClientDeletePollerResponse.Poller.Poll(ctx)
				if err != nil {
					t.Fatalf("Request error: %v", err)
				}
				if securityRulesClientDeletePollerResponse.Poller.Done() {
					_, err = securityRulesClientDeletePollerResponse.Poller.FinalResponse(ctx)
					if err != nil {
						t.Fatalf("Request error: %v", err)
					}
					break
				}
			}
		} else {
			_, err = securityRulesClientDeletePollerResponse.PollUntilDone(ctx, 10*time.Second)
			if err != nil {
				t.Fatalf("Request error: %v", err)
			}
		}
	}
}

func cleanup(t *testing.T) {
}
