//go:build go1.16
// +build go1.16

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package virtualnetwork_test

import (
	"context"
	"testing"

	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/internal/recording"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/scenario_test"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
)

var (
	ctx                context.Context
	cred               azcore.TokenCredential
	pathToPackage      = "sdk/resourcemanager/network/armnetwork/scenario_test/virtualnetwork/testdata"
	options            *arm.ClientOptions
	resourceGroup      *armresources.ResourceGroup
	resourceName       string
	virtualNetworkName = "scenarios_vn"
	location           = scenario_test.GetEnv("LOCATION", "eastus")
	resourceGroupName  = scenario_test.GetEnv("RESOURCE_GROUP_NAME", "")
	subscriptionId     = scenario_test.GetEnv("SUBSCRIPTION_ID", scenario_test.GetEnv("AZURE_SUBSCRIPTION_ID", ""))
)

func TestVirtualnetwork(t *testing.T) {
	// Setup for test
	scenario_test.StartRecording(t, pathToPackage)
	ctx = context.Background()
	options = scenario_test.CreateArmOptions(t)
	cred = scenario_test.CreateCred(t, ctx, options)
	resourceGroup = scenario_test.CreateResourceGroup(t, ctx, cred, subscriptionId, location, options)
	resourceGroupName = *resourceGroup.Name
	// Clenup for test
	t.Cleanup(func() {
		scenario_test.DeleteResourceGroup(t, ctx, cred, subscriptionId, resourceGroupName, options)
		scenario_test.StopRecording(t)
	})
	prepare(t)
	scenarioVirtualnetworks(t)
	cleanup(t)
}

func prepare(t *testing.T) {
	// From step Generate_Unique_Name
	{
		template := map[string]interface{}{
			"$schema":        "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
			"contentVersion": "1.0.0.0",
			"outputs": map[string]interface{}{
				"resourceName": map[string]interface{}{
					"type":  "string",
					"value": "[variables('name').value]",
				},
			},
			"resources": []interface{}{},
			"variables": map[string]interface{}{
				"name": map[string]interface{}{
					"type": "string",
					"metadata": map[string]interface{}{
						"description": "Name of the Resource Group.",
					},
					"value": "[concat('sw',uniqueString(resourceGroup().id))]",
				},
			},
		}
		params := map[string]interface{}{}
		deploymentExtend, err := scenario_test.CreateDeployment(ctx, cred, options, subscriptionId, resourceGroupName, "Generate_Unique_Name", template, params)
		if err != nil {
			t.Fatalf("Deployment error: %v", err)
		}
		resourceName = deploymentExtend.Properties.Outputs["resourceName"].(map[string]interface{})["value"].(string)
	}
}

func scenarioVirtualnetworks(t *testing.T) {
	// From step VirtualNetworks_BeginCreateOrUpdate
	virtualNetworksClient := armnetwork.NewVirtualNetworksClient(subscriptionId, cred, options)
	{
		virtualNetworksClientCreateOrUpdatePollerResponse, err := virtualNetworksClient.BeginCreateOrUpdate(ctx,
			resourceGroupName,
			virtualNetworkName,
			armnetwork.VirtualNetwork{
				Location: to.StringPtr(location),
				Properties: &armnetwork.VirtualNetworkPropertiesFormat{
					AddressSpace: &armnetwork.AddressSpace{
						AddressPrefixes: []*string{
							to.StringPtr("10.0.0.0/16")},
					},
					FlowTimeoutInMinutes: to.Int32Ptr(10),
				},
			},
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		var response armnetwork.VirtualNetworksClientCreateOrUpdateResponse
		if recording.GetRecordMode() == recording.PlaybackMode {
			for {
				_, err = virtualNetworksClientCreateOrUpdatePollerResponse.Poller.Poll(ctx)
				if err != nil {
					t.Fatalf("Request error: %v", err)
				}
				if virtualNetworksClientCreateOrUpdatePollerResponse.Poller.Done() {
					response, err = virtualNetworksClientCreateOrUpdatePollerResponse.Poller.FinalResponse(ctx)
					if err != nil {
						t.Fatalf("Request error: %v", err)
					}
					break
				}
			}
		} else {
			response, err = virtualNetworksClientCreateOrUpdatePollerResponse.PollUntilDone(ctx, 10*time.Second)
			if err != nil {
				t.Fatalf("Request error: %v", err)
			}
		}
		t.Logf("Response result: %#v\n", response.VirtualNetworksClientCreateOrUpdateResult)
	}

	// From step VirtualNetworks_CreateWithSubnet
	{
		virtualNetworksClientCreateOrUpdatePollerResponse, err := virtualNetworksClient.BeginCreateOrUpdate(ctx,
			resourceGroupName,
			virtualNetworkName,
			armnetwork.VirtualNetwork{
				Location: to.StringPtr(location),
				Properties: &armnetwork.VirtualNetworkPropertiesFormat{
					AddressSpace: &armnetwork.AddressSpace{
						AddressPrefixes: []*string{
							to.StringPtr("10.0.0.0/16")},
					},
					Subnets: []*armnetwork.Subnet{
						{
							Name: to.StringPtr("test-1"),
							Properties: &armnetwork.SubnetPropertiesFormat{
								AddressPrefix: to.StringPtr("10.0.0.0/24"),
							},
						}},
				},
			},
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		var response armnetwork.VirtualNetworksClientCreateOrUpdateResponse
		if recording.GetRecordMode() == recording.PlaybackMode {
			for {
				_, err = virtualNetworksClientCreateOrUpdatePollerResponse.Poller.Poll(ctx)
				if err != nil {
					t.Fatalf("Request error: %v", err)
				}
				if virtualNetworksClientCreateOrUpdatePollerResponse.Poller.Done() {
					response, err = virtualNetworksClientCreateOrUpdatePollerResponse.Poller.FinalResponse(ctx)
					if err != nil {
						t.Fatalf("Request error: %v", err)
					}
					break
				}
			}
		} else {
			response, err = virtualNetworksClientCreateOrUpdatePollerResponse.PollUntilDone(ctx, 10*time.Second)
			if err != nil {
				t.Fatalf("Request error: %v", err)
			}
		}
		t.Logf("Response result: %#v\n", response.VirtualNetworksClientCreateOrUpdateResult)
	}

	// From step VirtualNetworks_Get
	{
		virtualNetworksClientGetResponse, err := virtualNetworksClient.Get(ctx,
			resourceGroupName,
			virtualNetworkName,
			&armnetwork.VirtualNetworksClientGetOptions{Expand: nil})
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		t.Logf("Response result: %#v\n", virtualNetworksClientGetResponse.VirtualNetworksClientGetResult)
	}

	// From step VirtualNetworks_List
	{
		virtualNetworksClientListPager := virtualNetworksClient.List(resourceGroupName,
			nil)
		for virtualNetworksClientListPager.NextPage(ctx) {
			if err := virtualNetworksClientListPager.Err(); err != nil {
				t.Fatalf("Failed to advance page: %v", err)
			}
			for _, v := range virtualNetworksClientListPager.PageResponse().Value {
				t.Logf("Pager result: %#v\n", v)
			}
		}
	}

	// From step VirtualNetworks_ListAll
	{
		virtualNetworksClientListAllPager := virtualNetworksClient.ListAll(nil)
		for virtualNetworksClientListAllPager.NextPage(ctx) {
			if err := virtualNetworksClientListAllPager.Err(); err != nil {
				t.Fatalf("Failed to advance page: %v", err)
			}
			for _, v := range virtualNetworksClientListAllPager.PageResponse().Value {
				t.Logf("Pager result: %#v\n", v)
			}
		}
	}

	// From step VirtualNetworks_ListUsage
	{
		virtualNetworksClientListUsagePager := virtualNetworksClient.ListUsage(resourceGroupName,
			virtualNetworkName,
			nil)
		for virtualNetworksClientListUsagePager.NextPage(ctx) {
			if err := virtualNetworksClientListUsagePager.Err(); err != nil {
				t.Fatalf("Failed to advance page: %v", err)
			}
			for _, v := range virtualNetworksClientListUsagePager.PageResponse().Value {
				t.Logf("Pager result: %#v\n", v)
			}
		}
	}

	// From step VirtualNetworks_Delete
	{
		virtualNetworksClientDeletePollerResponse, err := virtualNetworksClient.BeginDelete(ctx,
			resourceGroupName,
			virtualNetworkName,
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		if recording.GetRecordMode() == recording.PlaybackMode {
			for {
				_, err = virtualNetworksClientDeletePollerResponse.Poller.Poll(ctx)
				if err != nil {
					t.Fatalf("Request error: %v", err)
				}
				if virtualNetworksClientDeletePollerResponse.Poller.Done() {
					_, err = virtualNetworksClientDeletePollerResponse.Poller.FinalResponse(ctx)
					if err != nil {
						t.Fatalf("Request error: %v", err)
					}
					break
				}
			}
		} else {
			_, err = virtualNetworksClientDeletePollerResponse.PollUntilDone(ctx, 10*time.Second)
			if err != nil {
				t.Fatalf("Request error: %v", err)
			}
		}
	}
}

func cleanup(t *testing.T) {
}
