trigger: none

pr: none

# schedules:
#   - cron: "0 1 22-28 * Sat"
#     displayName: Daily release
#     branches:
#       include:
#         - main
#     always: true

variables:
  # - group: Release Secrets for GitHub
  - group: Alancere_Cred


stages:
  - stage:
    jobs:
      - job:
        displayName: Go Auto Release
        steps:
          - task: GoTool@0
            inputs:
              version: '1.19'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                #!/bin/bash
                set -ex
                
                export PATH=$PATH:$HOME/go/bin
                export AZURE_STORAGE_PRIMARY_ACCOUNT_KEY=$(azure-storage-account-key)
                export AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN=$(azure-devops-personal-access-token)
                
                #git config --global user.email "ReleaseHelper"
                #git config --global user.name "ReleaseHelper"
                
                echo $(System.DefaultWorkingDirectory)
                echo $(pwd)
                pwd
                ls -a
                cd ../
                git clone https://github.com/Azure/azure-sdk-for-go.git
                
                #go install github.com/Azure/azure-sdk-for-go/eng/tools/mgmtreport@latest
                cd eng/tools/mgmtreport && go build .
                
                mgmtreport -sdkpath=$(System.DefaultWorkingDirectory) -storageaccount=chenjieshistorage -storagecontainerblob=mgmtReport3.html

