//go:build go1.16
// +build go1.16

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package networkinterface_test

import (
	"context"
	"testing"

	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/internal/recording"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/scenario_test"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
)

var (
	ctx                context.Context
	cred               azcore.TokenCredential
	pathToPackage      = "sdk/resourcemanager/network/armnetwork/scenario_test/networkinterface/testdata"
	options            *arm.ClientOptions
	resourceGroup      *armresources.ResourceGroup
	resourceName       string
	virtualNetworkName = "scenarios_vn"
	location           = scenario_test.GetEnv("LOCATION", "eastus")
	resourceGroupName  = scenario_test.GetEnv("RESOURCE_GROUP_NAME", "")
	subscriptionId     = scenario_test.GetEnv("SUBSCRIPTION_ID", scenario_test.GetEnv("AZURE_SUBSCRIPTION_ID", ""))
)

func TestNetworkinterface(t *testing.T) {
	// Setup for test
	scenario_test.StartRecording(t, pathToPackage)
	ctx = context.Background()
	options = scenario_test.CreateArmOptions(t)
	cred = scenario_test.CreateCred(t, ctx, options)
	resourceGroup = scenario_test.CreateResourceGroup(t, ctx, cred, subscriptionId, location, options)
	resourceGroupName = *resourceGroup.Name
	// Clenup for test
	t.Cleanup(func() {
		scenario_test.DeleteResourceGroup(t, ctx, cred, subscriptionId, resourceGroupName, options)
		scenario_test.StopRecording(t)
	})
	prepare(t)
	scenarioVritualnetworkinterface(t)
	cleanup(t)
}

func prepare(t *testing.T) {
	// From step Generate_Unique_Name
	{
		template := map[string]interface{}{
			"$schema":        "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
			"contentVersion": "1.0.0.0",
			"outputs": map[string]interface{}{
				"resourceName": map[string]interface{}{
					"type":  "string",
					"value": "[variables('name').value]",
				},
			},
			"resources": []interface{}{},
			"variables": map[string]interface{}{
				"name": map[string]interface{}{
					"type": "string",
					"metadata": map[string]interface{}{
						"description": "Name of the Resource Group.",
					},
					"value": "[concat('sw',uniqueString(resourceGroup().id))]",
				},
			},
		}
		params := map[string]interface{}{}
		deploymentExtend, err := scenario_test.CreateDeployment(ctx, cred, options, subscriptionId, resourceGroupName, "Generate_Unique_Name", template, params)
		if err != nil {
			t.Fatalf("Deployment error: %v", err)
		}
		resourceName = deploymentExtend.Properties.Outputs["resourceName"].(map[string]interface{})["value"].(string)
	}
}

func scenarioVritualnetworkinterface(t *testing.T) {
	var publicIP string
	var subnetID string
	// From step VirtualNetworks_CreateWithSubnet
	virtualNetworksClient := armnetwork.NewVirtualNetworksClient(subscriptionId, cred, options)
	{
		virtualNetworksClientCreateOrUpdatePollerResponse, err := virtualNetworksClient.BeginCreateOrUpdate(ctx,
			resourceGroupName,
			"test-vnet",
			armnetwork.VirtualNetwork{
				Location: to.StringPtr(location),
				Properties: &armnetwork.VirtualNetworkPropertiesFormat{
					AddressSpace: &armnetwork.AddressSpace{
						AddressPrefixes: []*string{
							to.StringPtr("10.0.0.0/16")},
					},
					Subnets: []*armnetwork.Subnet{
						{
							Name: to.StringPtr("test-1"),
							Properties: &armnetwork.SubnetPropertiesFormat{
								AddressPrefix: to.StringPtr("10.0.0.0/24"),
							},
						}},
				},
			},
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		var response armnetwork.VirtualNetworksClientCreateOrUpdateResponse
		if recording.GetRecordMode() == recording.PlaybackMode {
			for {
				_, err = virtualNetworksClientCreateOrUpdatePollerResponse.Poller.Poll(ctx)
				if err != nil {
					t.Fatalf("Request error: %v", err)
				}
				if virtualNetworksClientCreateOrUpdatePollerResponse.Poller.Done() {
					response, err = virtualNetworksClientCreateOrUpdatePollerResponse.Poller.FinalResponse(ctx)
					if err != nil {
						t.Fatalf("Request error: %v", err)
					}
					break
				}
			}
		} else {
			response, err = virtualNetworksClientCreateOrUpdatePollerResponse.PollUntilDone(ctx, 10*time.Second)
			if err != nil {
				t.Fatalf("Request error: %v", err)
			}
		}
		t.Logf("Response result: %#v\n", response.VirtualNetworksClientCreateOrUpdateResult)
		subnetID = *response.Properties.Subnets[0].ID
	}

	// From step PublicIpAddress_CreateDefaults
	publicIPAddressesClient := armnetwork.NewPublicIPAddressesClient(subscriptionId, cred, options)
	{
		publicIPAddressesClientCreateOrUpdatePollerResponse, err := publicIPAddressesClient.BeginCreateOrUpdate(ctx,
			resourceGroupName,
			"test-ip",
			armnetwork.PublicIPAddress{
				Location: to.StringPtr(location),
			},
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		var response armnetwork.PublicIPAddressesClientCreateOrUpdateResponse
		if recording.GetRecordMode() == recording.PlaybackMode {
			for {
				_, err = publicIPAddressesClientCreateOrUpdatePollerResponse.Poller.Poll(ctx)
				if err != nil {
					t.Fatalf("Request error: %v", err)
				}
				if publicIPAddressesClientCreateOrUpdatePollerResponse.Poller.Done() {
					response, err = publicIPAddressesClientCreateOrUpdatePollerResponse.Poller.FinalResponse(ctx)
					if err != nil {
						t.Fatalf("Request error: %v", err)
					}
					break
				}
			}
		} else {
			response, err = publicIPAddressesClientCreateOrUpdatePollerResponse.PollUntilDone(ctx, 10*time.Second)
			if err != nil {
				t.Fatalf("Request error: %v", err)
			}
		}
		t.Logf("Response result: %#v\n", response.PublicIPAddressesClientCreateOrUpdateResult)
		publicIP = *response.ID
	}

	// From step NetworkInterface_Create
	interfacesClient := armnetwork.NewInterfacesClient(subscriptionId, cred, options)
	{
		interfacesClientCreateOrUpdatePollerResponse, err := interfacesClient.BeginCreateOrUpdate(ctx,
			resourceGroupName,
			"test-nic",
			armnetwork.Interface{
				ID:       to.StringPtr("/subscriptions/" + subscriptionId + "/resourceGroups/" + resourceGroupName + "/providers/Microsoft.Network/networkInterfaces/test-nic"),
				Location: to.StringPtr(location),
				Properties: &armnetwork.InterfacePropertiesFormat{
					DNSSettings: &armnetwork.InterfaceDNSSettings{
						DNSServers: []*string{},
					},
					EnableAcceleratedNetworking: to.BoolPtr(true),
					EnableIPForwarding:          to.BoolPtr(false),
					IPConfigurations: []*armnetwork.InterfaceIPConfiguration{
						{
							ID:   to.StringPtr("/subscriptions/" + subscriptionId + "/resourceGroups/" + resourceGroupName + "/providers/Microsoft.Network/networkInterfaces/test-nic/ipConfigurations/ipconfig1"),
							Name: to.StringPtr("ipconfig1"),
							Properties: &armnetwork.InterfaceIPConfigurationPropertiesFormat{
								Primary:                   to.BoolPtr(true),
								PrivateIPAddress:          to.StringPtr("172.20.2.4"),
								PrivateIPAddressVersion:   armnetwork.IPVersionIPv4.ToPtr(),
								PrivateIPAllocationMethod: armnetwork.IPAllocationMethodDynamic.ToPtr(),
								PublicIPAddress: &armnetwork.PublicIPAddress{
									ID: to.StringPtr(publicIP),
								},
								Subnet: &armnetwork.Subnet{
									ID: to.StringPtr(subnetID),
								},
							},
						}},
				},
			},
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		var response armnetwork.InterfacesClientCreateOrUpdateResponse
		if recording.GetRecordMode() == recording.PlaybackMode {
			for {
				_, err = interfacesClientCreateOrUpdatePollerResponse.Poller.Poll(ctx)
				if err != nil {
					t.Fatalf("Request error: %v", err)
				}
				if interfacesClientCreateOrUpdatePollerResponse.Poller.Done() {
					response, err = interfacesClientCreateOrUpdatePollerResponse.Poller.FinalResponse(ctx)
					if err != nil {
						t.Fatalf("Request error: %v", err)
					}
					break
				}
			}
		} else {
			response, err = interfacesClientCreateOrUpdatePollerResponse.PollUntilDone(ctx, 10*time.Second)
			if err != nil {
				t.Fatalf("Request error: %v", err)
			}
		}
		t.Logf("Response result: %#v\n", response.InterfacesClientCreateOrUpdateResult)
	}

	// From step NetworkInterface_Get
	{
		interfacesClientGetResponse, err := interfacesClient.Get(ctx,
			resourceGroupName,
			"test-nic",
			&armnetwork.InterfacesClientGetOptions{Expand: nil})
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		t.Logf("Response result: %#v\n", interfacesClientGetResponse.InterfacesClientGetResult)
	}

	// From step NetworkInterface_List
	{
		interfacesClientListPager := interfacesClient.List(resourceGroupName,
			nil)
		for interfacesClientListPager.NextPage(ctx) {
			if err := interfacesClientListPager.Err(); err != nil {
				t.Fatalf("Failed to advance page: %v", err)
			}
			for _, v := range interfacesClientListPager.PageResponse().Value {
				t.Logf("Pager result: %#v\n", v)
			}
		}
	}

	// From step NetworkInterface_ListAll
	{
		interfacesClientListAllPager := interfacesClient.ListAll(nil)
		for interfacesClientListAllPager.NextPage(ctx) {
			if err := interfacesClientListAllPager.Err(); err != nil {
				t.Fatalf("Failed to advance page: %v", err)
			}
			for _, v := range interfacesClientListAllPager.PageResponse().Value {
				t.Logf("Pager result: %#v\n", v)
			}
		}
	}

	// From step NetworkInterface_Delete
	{
		interfacesClientDeletePollerResponse, err := interfacesClient.BeginDelete(ctx,
			resourceGroupName,
			"test-nic",
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		if recording.GetRecordMode() == recording.PlaybackMode {
			for {
				_, err = interfacesClientDeletePollerResponse.Poller.Poll(ctx)
				if err != nil {
					t.Fatalf("Request error: %v", err)
				}
				if interfacesClientDeletePollerResponse.Poller.Done() {
					_, err = interfacesClientDeletePollerResponse.Poller.FinalResponse(ctx)
					if err != nil {
						t.Fatalf("Request error: %v", err)
					}
					break
				}
			}
		} else {
			_, err = interfacesClientDeletePollerResponse.PollUntilDone(ctx, 10*time.Second)
			if err != nil {
				t.Fatalf("Request error: %v", err)
			}
		}
	}
}

func cleanup(t *testing.T) {
}
