trigger:
  branches:
    exclude:
      - '*'

# avoid being triggered as part of CI check
pr:
  branches:
    exclude:
      - '*'

schedules:
  - cron: "0,30 1-9 * * *"
    displayName: Daily release
    branches:
      include:
      - main
    always: true

variables:
  # - group: Release Secrets for GitHub
  - group: Alancere_Cred

stages:
  - stage: 
    jobs:
    - job: 
      displayName: Go Auto Release
      steps:
        - task: GoTool@0
          inputs:
            version: '1.18.2'
        
        - template: /eng/pipelines/templates/steps/create-go-workspace.yml

        - script: |
            echo $GO_WORKSPACE_PATH
            echo $GO_PATH
            go install github.com/Azure/azure-sdk-for-go/eng/tools/generator@latest
            
            cd $GO_WORKSPACE_PATH
            git log -1

            cd ../
            git clone https://github.com/Azure/azure-rest-api-specs.git

            generator issue -t $(azuresdk-github-pat) > sdk-release.json
            cat sdk-release.json