//go:build go1.16
// +build go1.16

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package loadbalancer_test

import (
	"context"
	"testing"

	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/internal/recording"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/scenario_test"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
)

var (
	ctx                context.Context
	cred               azcore.TokenCredential
	pathToPackage      = "sdk/resourcemanager/network/armnetwork/scenario_test/loadbalancer/testdata"
	options            *arm.ClientOptions
	resourceGroup      *armresources.ResourceGroup
	resourceName       string
	virtualNetworkName = "scenarios_vn"
	location           = scenario_test.GetEnv("LOCATION", "eastus")
	resourceGroupName  = scenario_test.GetEnv("RESOURCE_GROUP_NAME", "")
	subscriptionId     = scenario_test.GetEnv("SUBSCRIPTION_ID", scenario_test.GetEnv("AZURE_SUBSCRIPTION_ID", ""))
)

func TestLoadbalancer(t *testing.T) {
	// Setup for test
	scenario_test.StartRecording(t, pathToPackage)
	ctx = context.Background()
	options = scenario_test.CreateArmOptions(t)
	cred = scenario_test.CreateCred(t, ctx, options)
	resourceGroup = scenario_test.CreateResourceGroup(t, ctx, cred, subscriptionId, location, options)
	resourceGroupName = *resourceGroup.Name
	// Clenup for test
	t.Cleanup(func() {
		scenario_test.DeleteResourceGroup(t, ctx, cred, subscriptionId, resourceGroupName, options)
		scenario_test.StopRecording(t)
	})
	prepare(t)
	scenarioLoadbalancers(t)
	cleanup(t)
}

func prepare(t *testing.T) {
	// From step Generate_Unique_Name
	{
		template := map[string]interface{}{
			"$schema":        "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
			"contentVersion": "1.0.0.0",
			"outputs": map[string]interface{}{
				"resourceName": map[string]interface{}{
					"type":  "string",
					"value": "[variables('name').value]",
				},
			},
			"resources": []interface{}{},
			"variables": map[string]interface{}{
				"name": map[string]interface{}{
					"type": "string",
					"metadata": map[string]interface{}{
						"description": "Name of the Resource Group.",
					},
					"value": "[concat('sw',uniqueString(resourceGroup().id))]",
				},
			},
		}
		params := map[string]interface{}{}
		deploymentExtend, err := scenario_test.CreateDeployment(ctx, cred, options, subscriptionId, resourceGroupName, "Generate_Unique_Name", template, params)
		if err != nil {
			t.Fatalf("Deployment error: %v", err)
		}
		resourceName = deploymentExtend.Properties.Outputs["resourceName"].(map[string]interface{})["value"].(string)
	}
}

func scenarioLoadbalancers(t *testing.T) {
	var subnetID string
	// From step VirtualNetwork_BeginCreateOrUpdat
	virtualNetworksClient := armnetwork.NewVirtualNetworksClient(subscriptionId, cred, options)
	{
		virtualNetworksClientCreateOrUpdatePollerResponse, err := virtualNetworksClient.BeginCreateOrUpdate(ctx,
			resourceGroupName,
			virtualNetworkName,
			armnetwork.VirtualNetwork{
				Location: to.StringPtr(location),
				Properties: &armnetwork.VirtualNetworkPropertiesFormat{
					AddressSpace: &armnetwork.AddressSpace{
						AddressPrefixes: []*string{
							to.StringPtr("10.0.0.0/16")},
					},
					FlowTimeoutInMinutes: to.Int32Ptr(10),
				},
			},
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		var response armnetwork.VirtualNetworksClientCreateOrUpdateResponse
		if recording.GetRecordMode() == recording.PlaybackMode {
			for {
				_, err = virtualNetworksClientCreateOrUpdatePollerResponse.Poller.Poll(ctx)
				if err != nil {
					t.Fatalf("Request error: %v", err)
				}
				if virtualNetworksClientCreateOrUpdatePollerResponse.Poller.Done() {
					response, err = virtualNetworksClientCreateOrUpdatePollerResponse.Poller.FinalResponse(ctx)
					if err != nil {
						t.Fatalf("Request error: %v", err)
					}
					break
				}
			}
		} else {
			response, err = virtualNetworksClientCreateOrUpdatePollerResponse.PollUntilDone(ctx, 10*time.Second)
			if err != nil {
				t.Fatalf("Request error: %v", err)
			}
		}
		t.Logf("Response result: %#v\n", response.VirtualNetworksClientCreateOrUpdateResult)
	}

	// From step Subnets_BeginCreateOrUpdate
	subnetsClient := armnetwork.NewSubnetsClient(subscriptionId, cred, options)
	{
		subnetsClientCreateOrUpdatePollerResponse, err := subnetsClient.BeginCreateOrUpdate(ctx,
			resourceGroupName,
			virtualNetworkName,
			"subnet1",
			armnetwork.Subnet{
				Properties: &armnetwork.SubnetPropertiesFormat{
					AddressPrefix: to.StringPtr("10.0.0.0/16"),
				},
			},
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		var response armnetwork.SubnetsClientCreateOrUpdateResponse
		if recording.GetRecordMode() == recording.PlaybackMode {
			for {
				_, err = subnetsClientCreateOrUpdatePollerResponse.Poller.Poll(ctx)
				if err != nil {
					t.Fatalf("Request error: %v", err)
				}
				if subnetsClientCreateOrUpdatePollerResponse.Poller.Done() {
					response, err = subnetsClientCreateOrUpdatePollerResponse.Poller.FinalResponse(ctx)
					if err != nil {
						t.Fatalf("Request error: %v", err)
					}
					break
				}
			}
		} else {
			response, err = subnetsClientCreateOrUpdatePollerResponse.PollUntilDone(ctx, 10*time.Second)
			if err != nil {
				t.Fatalf("Request error: %v", err)
			}
		}
		t.Logf("Response result: %#v\n", response.SubnetsClientCreateOrUpdateResult)
		subnetID = *response.ID
	}

	// From step LoadBalancer_Create
	loadBalancersClient := armnetwork.NewLoadBalancersClient(subscriptionId, cred, options)
	{
		loadBalancersClientCreateOrUpdatePollerResponse, err := loadBalancersClient.BeginCreateOrUpdate(ctx,
			resourceGroupName,
			"lb",
			armnetwork.LoadBalancer{
				ID:       to.StringPtr("/subscriptions/" + subscriptionId + "/resourceGroups/" + resourceGroupName + "/providers/Microsoft.Network/loadBalancers/lb"),
				Location: to.StringPtr(location),
				Properties: &armnetwork.LoadBalancerPropertiesFormat{
					BackendAddressPools: []*armnetwork.BackendAddressPool{
						{
							ID:         to.StringPtr("/subscriptions/" + subscriptionId + "/resourceGroups/" + resourceGroupName + "/providers/Microsoft.Network/loadBalancers/lb/backendAddressPools/be-lb"),
							Name:       to.StringPtr("be-lb"),
							Properties: &armnetwork.BackendAddressPoolPropertiesFormat{},
						}},
					FrontendIPConfigurations: []*armnetwork.FrontendIPConfiguration{
						{
							ID:   to.StringPtr("/subscriptions/" + subscriptionId + "/resourceGroups/" + resourceGroupName + "/providers/Microsoft.Network/loadBalancers/lb/frontendIPConfigurations/fe-lb"),
							Name: to.StringPtr("fe-lb"),
							Properties: &armnetwork.FrontendIPConfigurationPropertiesFormat{
								PrivateIPAddress:          to.StringPtr("10.0.1.4"),
								PrivateIPAllocationMethod: armnetwork.IPAllocationMethodDynamic.ToPtr(),
								Subnet: &armnetwork.Subnet{
									ID: to.StringPtr(subnetID),
								},
							},
						}},
					InboundNatPools: []*armnetwork.InboundNatPool{},
					InboundNatRules: []*armnetwork.InboundNatRule{
						{
							ID:   to.StringPtr("/subscriptions/" + subscriptionId + "/resourceGroups/" + resourceGroupName + "/providers/Microsoft.Network/loadBalancers/lb/inboundNatRules/in-nat-rule"),
							Name: to.StringPtr("in-nat-rule"),
							Properties: &armnetwork.InboundNatRulePropertiesFormat{
								BackendPort:      to.Int32Ptr(3389),
								EnableFloatingIP: to.BoolPtr(true),
								EnableTCPReset:   to.BoolPtr(false),
								FrontendIPConfiguration: &armnetwork.SubResource{
									ID: to.StringPtr("/subscriptions/" + subscriptionId + "/resourceGroups/" + resourceGroupName + "/providers/Microsoft.Network/loadBalancers/lb/frontendIPConfigurations/fe-lb"),
								},
								FrontendPort:         to.Int32Ptr(3389),
								IdleTimeoutInMinutes: to.Int32Ptr(15),
								Protocol:             armnetwork.TransportProtocolTCP.ToPtr(),
							},
						}},
					LoadBalancingRules: []*armnetwork.LoadBalancingRule{
						{
							ID:   to.StringPtr("/subscriptions/" + subscriptionId + "/resourceGroups/" + resourceGroupName + "/providers/Microsoft.Network/loadBalancers/lb/loadBalancingRules/rulelb"),
							Name: to.StringPtr("rulelb"),
							Properties: &armnetwork.LoadBalancingRulePropertiesFormat{
								BackendAddressPool: &armnetwork.SubResource{
									ID: to.StringPtr("/subscriptions/" + subscriptionId + "/resourceGroups/" + resourceGroupName + "/providers/Microsoft.Network/loadBalancers/lb/backendAddressPools/be-lb"),
								},
								BackendPort:         to.Int32Ptr(80),
								DisableOutboundSnat: to.BoolPtr(false),
								EnableFloatingIP:    to.BoolPtr(true),
								EnableTCPReset:      to.BoolPtr(false),
								FrontendIPConfiguration: &armnetwork.SubResource{
									ID: to.StringPtr("/subscriptions/" + subscriptionId + "/resourceGroups/" + resourceGroupName + "/providers/Microsoft.Network/loadBalancers/lb/frontendIPConfigurations/fe-lb"),
								},
								FrontendPort:         to.Int32Ptr(80),
								IdleTimeoutInMinutes: to.Int32Ptr(15),
								LoadDistribution:     armnetwork.LoadDistributionDefault.ToPtr(),
								Probe: &armnetwork.SubResource{
									ID: to.StringPtr("/subscriptions/" + subscriptionId + "/resourceGroups/" + resourceGroupName + "/providers/Microsoft.Network/loadBalancers/lb/probes/probe-lb"),
								},
								Protocol: armnetwork.TransportProtocolTCP.ToPtr(),
							},
						}},
					Probes: []*armnetwork.Probe{
						{
							ID:   to.StringPtr("/subscriptions/" + subscriptionId + "/resourceGroups/" + resourceGroupName + "/providers/Microsoft.Network/loadBalancers/lb/probes/probe-lb"),
							Name: to.StringPtr("probe-lb"),
							Properties: &armnetwork.ProbePropertiesFormat{
								IntervalInSeconds: to.Int32Ptr(15),
								NumberOfProbes:    to.Int32Ptr(2),
								Port:              to.Int32Ptr(80),
								RequestPath:       to.StringPtr("healthcheck.aspx"),
								Protocol:          armnetwork.ProbeProtocolHTTP.ToPtr(),
							},
						}},
				},
				SKU: &armnetwork.LoadBalancerSKU{
					Name: armnetwork.LoadBalancerSKUNameBasic.ToPtr(),
				},
			},
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		var response armnetwork.LoadBalancersClientCreateOrUpdateResponse
		if recording.GetRecordMode() == recording.PlaybackMode {
			for {
				_, err = loadBalancersClientCreateOrUpdatePollerResponse.Poller.Poll(ctx)
				if err != nil {
					t.Fatalf("Request error: %v", err)
				}
				if loadBalancersClientCreateOrUpdatePollerResponse.Poller.Done() {
					response, err = loadBalancersClientCreateOrUpdatePollerResponse.Poller.FinalResponse(ctx)
					if err != nil {
						t.Fatalf("Request error: %v", err)
					}
					break
				}
			}
		} else {
			response, err = loadBalancersClientCreateOrUpdatePollerResponse.PollUntilDone(ctx, 10*time.Second)
			if err != nil {
				t.Fatalf("Request error: %v", err)
			}
		}
		t.Logf("Response result: %#v\n", response.LoadBalancersClientCreateOrUpdateResult)
	}

	// From step LoadBalancer_Get
	{
		loadBalancersClientGetResponse, err := loadBalancersClient.Get(ctx,
			resourceGroupName,
			"lb",
			&armnetwork.LoadBalancersClientGetOptions{Expand: nil})
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		t.Logf("Response result: %#v\n", loadBalancersClientGetResponse.LoadBalancersClientGetResult)
	}

	// From step LoadBalancer_List
	{
		loadBalancersClientListPager := loadBalancersClient.List(resourceGroupName,
			nil)
		for loadBalancersClientListPager.NextPage(ctx) {
			if err := loadBalancersClientListPager.Err(); err != nil {
				t.Fatalf("Failed to advance page: %v", err)
			}
			for _, v := range loadBalancersClientListPager.PageResponse().Value {
				t.Logf("Pager result: %#v\n", v)
			}
		}
	}

	// From step LoadBalancer_Delete
	{
		loadBalancersClientDeletePollerResponse, err := loadBalancersClient.BeginDelete(ctx,
			resourceGroupName,
			"lb",
			nil)
		if err != nil {
			t.Fatalf("Request error: %v", err)
		}
		if recording.GetRecordMode() == recording.PlaybackMode {
			for {
				_, err = loadBalancersClientDeletePollerResponse.Poller.Poll(ctx)
				if err != nil {
					t.Fatalf("Request error: %v", err)
				}
				if loadBalancersClientDeletePollerResponse.Poller.Done() {
					_, err = loadBalancersClientDeletePollerResponse.Poller.FinalResponse(ctx)
					if err != nil {
						t.Fatalf("Request error: %v", err)
					}
					break
				}
			}
		} else {
			_, err = loadBalancersClientDeletePollerResponse.PollUntilDone(ctx, 10*time.Second)
			if err != nil {
				t.Fatalf("Request error: %v", err)
			}
		}
	}
}

func cleanup(t *testing.T) {
}
